### ISSUE TITLE
Integration on Discord Bot

### ISSUE THREAD

**Issue by mgiannopoulos24** [ChatTeach/FreeGPT#10]
Hi there.

How can I give prompts to this gpt from a discord bot?. For example the discord user will ping my bot giving it a prompt and then the prompt should be sent on the FreeGPT.

Thanks in advance

**Comment by KnuxTheFixer** [comment]
You dont need to write your own bot for that, [Someone has already done it for you](https://github.com/Ruu3f/freeGPT)

**Comment by mgiannopoulos24** [comment]
Okay thank you very much.
