### ISSUE TITLE
Installation Issue (Python-3.12.1) - MAC

### ISSUE THREAD

**Issue by subu1979** [ChatTeach/FreeGPT#14]
studio@Subramanyam freegpt-webui % python3
Python 3.12.1 (main, Dec  9 2023, 08:07:48) [Clang 15.0.0 (clang-1500.0.40.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> quit()

studio@Subramanyam freegpt-webui % which python3
/opt/local/bin/python3
studio@Subramanyam freegpt-webui % pip3 install -r requirements.txt
Defaulting to user installation because normal site-packages is not writeable
Collecting websocket-client
  Using cached websocket_client-1.8.0-py3-none-any.whl (58 kB)
Collecting requests
  Using cached requests-2.32.3-py3-none-any.whl (64 kB)
Collecting tls-client
  Using cached tls_client-1.0.1-py3-none-any.whl (41.3 MB)
Collecting pypasser
  Using cached PyPasser-0.0.5.tar.gz (10 kB)
Collecting names
  Using cached names-0.3.0.tar.gz (789 kB)
Collecting colorama
  Using cached colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Collecting curl_cffi
  Using cached curl_cffi-0.6.4-cp38-abi3-macosx_10_9_x86_64.whl (4.7 MB)
Collecting aiohttp
  Using cached aiohttp-3.9.5-cp39-cp39-macosx_10_9_x86_64.whl (401 kB)
Collecting flask
  Using cached flask-3.0.3-py3-none-any.whl (101 kB)
Collecting flask_cors
  Using cached Flask_Cors-4.0.1-py2.py3-none-any.whl (14 kB)
Collecting flask-babel
  Using cached flask_babel-4.0.0-py3-none-any.whl (9.6 kB)
Collecting streamlit
  Using cached streamlit-1.35.0-py2.py3-none-any.whl (8.6 MB)
Collecting selenium
  Using cached selenium-4.21.0-py3-none-any.whl (9.5 MB)
Collecting fake-useragent
  Using cached fake_useragent-1.5.1-py3-none-any.whl (17 kB)
Collecting twocaptcha
  Using cached TwoCaptcha-0.0.1.tar.gz (2.9 kB)
Collecting pydantic
  Using cached pydantic-2.7.4-py3-none-any.whl (409 kB)
Collecting pymailtm
  Using cached pymailtm-1.1.1-py3-none-any.whl (19 kB)
Collecting Levenshtein
  Using cached Levenshtein-0.25.1-cp39-cp39-macosx_10_9_x86_64.whl (135 kB)
Collecting retrying
  Using cached retrying-1.3.4-py3-none-any.whl (11 kB)
ERROR: Could not find a version that satisfies the requirement mailgw_temporary_email (from versions: none)
ERROR: No matching distribution found for mailgw_temporary_email
WARNING: You are using pip version 21.2.4; however, version 24.0 is available.
You should consider upgrading via the '/Applications/Xcode.app/Contents/Developer/usr/bin/python3 -m pip install --upgrade pip' command.
studio@Subramanyam freegpt-webui %

**Comment by TrivCodez** [comment]
mailgw_temporary_email is not a package with pip.... try with brew iggg

**Comment by Adam-Developing** [comment]
pip install mail-gw
